# Generated by Django 2.2.7 on 2019-11-17 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('caption', models.TextField()),
                ('artist', models.CharField(max_length=100)),
                ('vibe', models.CharField(choices=[('everything', 'EVERYTHING'), ('party', 'PARTY'), ('chill', 'CHILL'), ('upbeat', 'UPBEAT'), ('moody', 'MOODY'), ('sensual', 'SENSUAL')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='sound.Post')),
            ],
        ),
    ]
